# Generated by Django 6.1 on 2026-09-22 11:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('registration_no', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
            ],
            options={
                'ordering': ['name'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('deleted_at__isnull', True), ('is_deleted', False)),
                            models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                            _connector='OR',
                        ),
                        name='organization_organization_soft_delete_state',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Owning cooperative.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='branches',
                        to='organization.organization',
                    ),
                ),
            ],
            options={'ordering': ['code']},
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
                (
                    'branch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='departments',
                        to='organization.branch',
                    ),
                ),
            ],
            options={
                'ordering': ['code'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('branch', 'code'), name='organization_department_branch_code_unique'
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('deleted_at__isnull', True), ('is_deleted', False)),
                            models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                            _connector='OR',
                        ),
                        name='organization_department_soft_delete_state',
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('deleted_at__isnull', True), ('is_deleted', False)),
                    models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                    _connector='OR',
                ),
                name='organization_branch_soft_delete_state',
            ),
        ),
    ]
