# Generated by Django 6.1 on 2026-09-22 12:04

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.core.money


class Migration(migrations.Migration):
    initial = True

    dependencies = [('members', '0001_initial'), ('organization', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                (
                    'side',
                    models.CharField(
                        choices=[
                            ('debit', 'Debit (assets & expenses increase on debit)'),
                            ('credit', 'Credit (liabilities, equity & income increase on credit)'),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('cash', 'Cash'),
                            ('bank', 'Bank'),
                            ('savings', 'Savings'),
                            ('loan', 'Loan'),
                            ('receivable', 'Receivable'),
                            ('payable', 'Payable'),
                            ('capital', 'Capital'),
                            ('revenue', 'Revenue'),
                            ('expense', 'Expense'),
                            ('other', 'Other'),
                        ],
                        default='other',
                        max_length=20,
                    ),
                ),
                ('is_system', models.BooleanField(default=False)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
            ],
            options={
                'ordering': ['code'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('deleted_at__isnull', True), ('is_deleted', False)),
                            models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                            _connector='OR',
                        ),
                        name='accounts_accounttype_soft_delete_state',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('account_no', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('allows_overdraft', models.BooleanField(default=False)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
                (
                    'branch',
                    models.ForeignKey(
                        blank=True,
                        help_text='Null for system / nominal accounts.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='accounts',
                        to='organization.branch',
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        blank=True,
                        help_text='Set for member-facing accounts.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='accounts',
                        to='members.member',
                    ),
                ),
                (
                    'account_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='accounts',
                        to='accounts.accounttype',
                    ),
                ),
            ],
            options={'ordering': ['account_no']},
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'current_balance',
                    apps.core.money.MoneyField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    'available_balance',
                    apps.core.money.MoneyField(decimal_places=2, default=0, max_digits=20),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'account',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='balance',
                        to='accounts.account',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            ('current_balance__gte', 0),
                            ('available_balance__gte', 0),
                            ('available_balance__lte', models.F('current_balance')),
                        ),
                        name='account_balance_non_negative',
                        violation_error_message='Balances must be non-negative with available balance not exceeding current balance.',
                    )
                ]
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('deleted_at__isnull', True), ('is_deleted', False)),
                    models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                    _connector='OR',
                ),
                name='accounts_account_soft_delete_state',
            ),
        ),
    ]
