# Generated by Django 6.1 on 2026-09-22 09:18

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('identity', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('member_no', models.CharField(blank=True, max_length=20, unique=True)),
                (
                    'user',
                    models.OneToOneField(
                        blank=True,
                        help_text='Optional login account linked to this member.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='member',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                (
                    'gender',
                    models.CharField(
                        blank=True,
                        choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')],
                        max_length=10,
                    ),
                ),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('join_date', models.DateField(default=django.utils.timezone.localdate)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        default='active',
                        max_length=20,
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={'ordering': ['-join_date']},
        )
    ]
