# Generated by Django 6.1 on 2026-09-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('identity', '0002_member')]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(
                blank=True, help_text='Contact phone number for the member.', max_length=15
            ),
        )
    ]
