# Generated by Django 6.1 on 2026-09-22 09:51

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [('identity', '0003_alter_member_phone')]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member', name='updated_at', field=models.DateTimeField(auto_now=True)
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(
                choices=[('active', 'Active'), ('inactive', 'Inactive')],
                db_index=True,
                default='active',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(
                choices=[('active', 'Active'), ('inactive', 'Inactive')],
                db_index=True,
                default='active',
                help_text='Status of the user account.',
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(
                condition=models.Q(('deleted_at__isnull', True), ('is_deleted', False))
                | models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                name='identity_member_soft_delete_state',
            ),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                condition=models.Q(('deleted_at__isnull', True), ('is_deleted', False))
                | models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                name='identity_user_soft_delete_state',
            ),
        ),
    ]
