# Generated by Django 6.1 on 2026-09-22 12:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('reference', models.CharField(blank=True, max_length=32, unique=True)),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('deposit', 'Deposit'),
                            ('withdrawal', 'Withdrawal'),
                            ('transfer', 'Transfer'),
                            ('reversal', 'Reversal'),
                            ('disbursement', 'Loan Disbursement'),
                            ('repayment', 'Loan Repayment'),
                            ('fee', 'Fee'),
                            ('interest', 'Interest Posting'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('initiated', 'Initiated'),
                            ('processing', 'Processing'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                            ('cancelled', 'Cancelled'),
                            ('reversed', 'Reversed'),
                        ],
                        db_index=True,
                        default='initiated',
                        max_length=20,
                    ),
                ),
                (
                    'source_channel',
                    models.CharField(
                        choices=[
                            ('api', 'API'),
                            ('web', 'Web Portal'),
                            ('cashier', 'Cashier'),
                            ('import', 'Bulk Import'),
                            ('bank', 'Bank Transfer'),
                        ],
                        default='api',
                        max_length=20,
                    ),
                ),
                (
                    'idempotency_key',
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True, unique=True
                    ),
                ),
                ('memo', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'branch',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='transactions',
                        to='organization.branch',
                    ),
                ),
                (
                    'requested_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ['-created_at']},
        )
    ]
