# Generated by Django 6.1 on 2026-09-22 12:04

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.core.money


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                (
                    'interest_rate',
                    models.DecimalField(
                        decimal_places=2, default=0, help_text='Annual rate %', max_digits=5
                    ),
                ),
                (
                    'min_opening_balance',
                    apps.core.money.MoneyField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
            ],
            options={
                'ordering': ['code'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('deleted_at__isnull', True), ('is_deleted', False)),
                            models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                            _connector='OR',
                        ),
                        name='savings_savingsproduct_soft_delete_state',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('account_no', models.CharField(max_length=32, unique=True)),
                ('opened_on', models.DateField(default=datetime.date.today)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
                (
                    'account',
                    models.OneToOneField(
                        help_text='Posting account behind this savings account.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='savings_account',
                        to='accounts.account',
                    ),
                ),
                (
                    'branch',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='savings_accounts',
                        to='organization.branch',
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='savings_accounts',
                        to='members.member',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='savings_accounts',
                        to='savings.savingsproduct',
                    ),
                ),
            ],
            options={
                'ordering': ['-opened_on'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('deleted_at__isnull', True), ('is_deleted', False)),
                            models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                            _connector='OR',
                        ),
                        name='savings_savingsaccount_soft_delete_state',
                    )
                ],
            },
        ),
    ]
