# Generated by Django 6.1 on 2026-09-22 12:04

import uuid

from django.db import migrations, models

import apps.core.money


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('journal_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=64)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('debit', apps.core.money.MoneyField(decimal_places=2, default=0, max_digits=20)),
                ('credit', apps.core.money.MoneyField(decimal_places=2, default=0, max_digits=20)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={'ordering': ['journal__created_at', 'id']},
        ),
    ]
