# Generated by Django 6.1 on 2026-09-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ledger', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='transaction',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='journal',
                to='transactions.transaction',
            ),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='ledger_entries',
                to='accounts.account',
            ),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='journal',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='entries',
                to='ledger.journal',
            ),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('credit__gte', 0),
                    ('debit__gte', 0),
                    models.Q(
                        models.Q(('credit', 0), ('debit__gt', 0)),
                        models.Q(('credit__gt', 0), ('debit', 0)),
                        _connector='OR',
                    ),
                ),
                name='ledger_entry_single_side',
                violation_error_message='A ledger entry must debit or credit a single account.',
            ),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(
                condition=models.Q(('credit__gte', 0), ('debit__gte', 0)),
                name='ledger_entry_non_negative',
                violation_error_message='Ledger amounts cannot be negative.',
            ),
        ),
    ]
