# Generated by Django 6.1 on 2026-09-23 04:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.money


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                (
                    'min_amount',
                    apps.core.money.MoneyField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    'max_amount',
                    apps.core.money.MoneyField(decimal_places=2, default=1000000, max_digits=20),
                ),
                (
                    'interest_rate',
                    models.DecimalField(
                        decimal_places=2, default=10, help_text='Annual rate %', max_digits=5
                    ),
                ),
                ('default_tenure_months', models.PositiveSmallIntegerField(default=12)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        db_index=True,
                        default='active',
                        max_length=20,
                    ),
                ),
            ],
            options={
                'ordering': ['code'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('max_amount__gte', models.F('min_amount'))),
                        name='loan_product_amount_range',
                        violation_error_message='Max amount must be >= min amount.',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('deleted_at__isnull', True), ('is_deleted', False)),
                            models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                            _connector='OR',
                        ),
                        name='loans_loanproduct_soft_delete_state',
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('loan_no', models.CharField(max_length=32, unique=True)),
                (
                    'principal',
                    apps.core.money.MoneyField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    'interest_rate',
                    models.DecimalField(
                        decimal_places=2, default=10, help_text='Annual rate %', max_digits=5
                    ),
                ),
                ('tenure_months', models.PositiveSmallIntegerField(default=12)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('requested', 'Requested'),
                            ('approved', 'Approved'),
                            ('disbursed', 'Disbursed'),
                            ('active', 'Active'),
                            ('closed', 'Closed'),
                            ('written_off', 'Written Off'),
                            ('cancelled', 'Cancelled'),
                        ],
                        db_index=True,
                        default='requested',
                        max_length=20,
                    ),
                ),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'principal_paid',
                    apps.core.money.MoneyField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    'interest_paid',
                    apps.core.money.MoneyField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='loans',
                        to='members.member',
                    ),
                ),
                (
                    'requested_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'savings_account',
                    models.ForeignKey(
                        help_text='Account used as repayment source.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='loans',
                        to='savings.savingsaccount',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='loans',
                        to='loans.loanproduct',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('principal__gte', 0)),
                        name='loan_principal_positive',
                        violation_error_message='Loan principal cannot be negative.',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(('deleted_at__isnull', True), ('is_deleted', False)),
                            models.Q(('deleted_at__isnull', False), ('is_deleted', True)),
                            _connector='OR',
                        ),
                        name='loans_loan_soft_delete_state',
                    ),
                ],
            },
        ),
    ]
