# Generated by Django 6.1 on 2026-09-23 04:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'action',
                    models.CharField(
                        choices=[
                            ('create', 'Create'),
                            ('update', 'Update'),
                            ('delete', 'Delete'),
                            ('post', 'Post'),
                            ('reverse', 'Reverse'),
                            ('approve', 'Approve'),
                            ('reject', 'Reject'),
                            ('cancel', 'Cancel'),
                            ('login', 'Login'),
                            ('logout', 'Logout'),
                            ('system', 'System'),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='audit_logs',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [
                    models.Index(
                        fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'
                    )
                ],
            },
        )
    ]
