# Generated by Django 6.1 on 2026-09-23 04:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'notification_type',
                    models.CharField(
                        choices=[
                            ('transaction', 'Transaction'),
                            ('approval', 'Approval'),
                            ('member', 'Member'),
                            ('loan', 'Loan'),
                            ('system', 'System'),
                        ],
                        default='system',
                        max_length=20,
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ['-created_at']},
        )
    ]
